config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/dashboard'

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :state, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
    
    def dashboard
        @project = Project.create(name: params[:name], description: params[:description], startdate: params[:startdate], finishdate: params[:finishdate], state: params[:state])

        if params[:state].present?
            @projects = Project.where('state = ?', params[:state])
        else
            @projects = Project.all
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestorproyectos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- NAVBAR -->
      <div class="container">
          <a href="/">Index</a>
          <%= link_to "Dashboard", pages_dashboard_path %>
      </div>

    <%= yield %>

    <!-- SCRIPT -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

app/views/pages/dashboard.html.erb
<nav class="navbar navbar-dark bg-primary justify-content-between">
    <a class="navbar-brand ps-5">Buscar proyecto</a>
    <form class="form-inline me-5">
        <select name="state" class="form-select mb-1" aria-label="Default select example">
            <option value="" selected>Abre este menu</option>
            <option value="propuesta">Propuesta</option>
            <option value="en_progreso">En progreso</option>
            <option value="terminado">Terminado</option>
        </select>
        <button class="btn btn-outline-light my-3 my-sm-0" type="submit">Buscar</button>
    </form>
</nav>

<div class="container py-4">
    <table class="table table-striped">
        <tr class="table-primary">
            <th scope="col">Nombre</th>
            <th scope="col">Descripción</th>
            <th scope="col">Estado del proyecto</th>
            <th scope="col">Fecha de inicio</th>
            <th scope="col">Fecha de finalización</th>
        </tr>
        <% @projects.each do |project| %>
            <tr>
                <td><%= project.name %></td>
                <td><%= project.description %></td>
                <td><%= project.state %></td>
                <td><%= project.startdate %></td>
                <td><%= project.finishdate %></td>
            </tr>
        <% end %>
    </table>
</div>

app/views/pages/index.html.erb
<div class="container pt-3">
    <h2>Crear Proyecto</h2>
    <form method="get" action="/pages/dashboard">
        <div class="mb-3">
            <label for="name" class="form-label">Nombre del proyecto</label>
            <input name="name" type="name" id="name" class="form-control">
        </div>

        <div class="mb-3">
            <label for="description" class="form-label">Descripción</label>
            <textarea name="description" type="description" class="form-control"></textarea>
        </div>

        <div class="mb-3">
            <label for="state" class="form-label">Estado del proyecto</label>
            <select name="state" id="state" class="form-select" aria-label="Default select example">
                <option value="propuesta" selected="selected">Propuesta</option>
                <option value="en_progreso">En progreso</option>
                <option value="terminado">Terminado</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="startdate" class="form-label">Fecha de inicio</label>
            <input name="startdate" type="startdate" class="form-control" placeholder="YYYY-MM-DD">
        </div>

        <div class="mb-3">
            <label for="finishdate" class="form-label">Fecha de finalización</label>
            <input name="finishdate" type="finishdate" class="form-control" placeholder="YYYY-MM-DD">
        </div>
        
        <button type="submit" class="btn btn-primary">Crear</button>

    </form>
</div>